version: '3'
services:
  postgres:
    container_name: postgres_habits
    image: postgres:12.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres